export const SEARCH_URL: string = "https://api.themoviedb.org/3/search/movie"
export const PIC_URL: string = "https://image.tmdb.org/t/p/original"
export const FLAG_URL: string = "http://purecatamphetamine.github.io/country-flag-icons/3x2/"
export const TRANDING_URL: string = "https://api.themoviedb.org/3/trending/movie/week"
export const DETAILS_URL: string = "https://api.themoviedb.org/3/movie/"
export const ADULT_ALERT: string = "/18_Plus.svg"
export const NO_IMAGE: string = "/noImage.webp"
export const SCROLL_TO_TOP: string = "/scrollToTop.svg"
export const adultGenreIds: number[] = [10749, 53, 9648, 27]
export const SCROLL_THRESHOLD = 700
